### ISSUE TITLE
Update homepage on pypi.

### ISSUE THREAD

**Issue by detrout** [jangler/readlike#2]
Hi,

On pypi readlike's homepage link still points to http://jangler.info/code/readlike but it looks like that site was shutdown sometime in 2016/2017 and that now some other entity owns the domain.

Is there a chance you could update the link on pypi to point to this repository instead?

**Comment by jangler** [comment]
Done! Also updated some other stale metadata. I really shouldn't have let that domain expire. 😛

**Comment by detrout** [comment]
Awesome. Thank you for fixing this so quickly!
